## **Toyota**

In [15]:
import pandas as pd

df = pd.read_csv("C:\\Users\\Harish\\Downloads\\Car_Sales_CSV\\car_sales.csv")

df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## **Toyota <= 5000**

In [21]:
df.to_csv("Cars_data.csv",index = False)

In [22]:
new_df = pd.read_csv("cars_data.csv")
new_df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [26]:
new_df["Price"] = new_df["Price"].replace(r"[$,]","",regex=True).astype(float)

toyota_df = new_df[(new_df["Make"]=="Toyota")&(new_df["Price"] <= 5000)]

toyota_df

     Make Colour  Odometer (KM)  Doors   Price
0  Toyota  White         150043      4  4000.0
5  Toyota  Green          99213      4  4500.0

## **Cars <= 5000**

In [28]:
car_datas = new_df[new_df["Price"]<= 5000]

car_datas

     Make Colour  Odometer (KM)  Doors   Price
0  Toyota  White         150043      4  4000.0
1   Honda    Red          87899      4  5000.0
4  Nissan  White         213095      4  3500.0
5  Toyota  Green          99213      4  4500.0